#! /usr/bin/env node

var template =
[
	'black',
	'red',
	'green',
	'yellow',
	'blue',
	'magenta',
	'cyan',
	'white'
]

var schema = require('stalwart')

/* bg only, because of xfce only accepts 16 colors, not {fg/bg} */
var base16 = schema.base16.colors.bg

var seq = []

seq = template.reduce(function (memo, name)
{
	return memo.concat([ base16[name].normal.hex() ])
},
seq)

seq = template.reduce(function (memo, name)
{
	return memo.concat([ base16[name].bright.hex() ])
},
seq)

var data =
{
	ColorForeground: base16.black.normal,
	ColorBackground: base16.white.bright,
	ColorPalette: seq.join(';'),
	ColorCursor: schema.accent,
	TabActivityColor: schema.accent
}

var { read, write } = require('fs-sync')
var mustache = require('mustache')

// var rct = read(__dirname + '/../template')
// var rc = mustache.render(rct, data)
// write(__dirname + '/../terminalrc', rc)

var rct = read(__dirname + '/../template.xml')
var rc = mustache.render(rct, data)
write(__dirname + '/../xfce4-terminal.xml', rc)
